apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-test-kustomize-app
    stage: dev
    type: demo
  name: flaskapp-test
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - flask-test-kustomize-app
      - key: type
        operator: In
        values:
          - demo
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-test-kustomize-app
        stage: dev
        type: demo
    spec:
      containers:
      - image: eu.gcr.io/[YOUR_PROJECT_ID]/flask_test/el-flaskapp-cloudbuild:latest
        name: flask-kustomize-container
        resources: {}
        imagePullPolicy: Always
        env:
        - name: LISTEN_ADDR
          value: $(HOST)
        - name: PORT
          value: $(PORT)
        - name: APP_LOCATION
          value: Luxembourg
        - name: DEPLOYED_CITY
          value: $(DEPLOYED_CITY)
        - name: ENVIRONMENT
          value: $(ENVIRONMENT)
        - name: APP_MODULE
          value: $(APP_MODULE)
        ports:
        - name: flask-http
          containerPort: 8010
          protocol: TCP